version: '3.7'

services:
    
    imgshare_php-httpd:
        build: 
              context: .
              dockerfile: Dockerfile 
        image: php:7.3-apache
        ports:
            - 80:80
        volumes:
            - "./imgshare:/var/www/html"

    imgshare_mariadb:
        image: mariadb:10.5.2
        ports:
            - 3306:3306
        volumes:
            - mariadb-volume:/var/lib/mysql
            - ./mysql_init/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
            - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 's3cr3t_pWd'
            MYSQL_DATABASE: 'imgshare'

volumes:
    mariadb-volume:
